// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdewacjsezyrtephyvcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZXdhY2pzZXp5cnRlcGh5dmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzEyOTEsImV4cCI6MjA3MjY0NzI5MX0.R42iaCwEzG8Cwk3fE5i842wvUf8gu487jXM02Ahfgb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});